"""
Auction Price Predictor + Dashboard
Run with: `streamlit run app.py`
Requires: model.pkl, encoder.pkl, feature_meta.json, cars_bids_clean.csv
           (all generated by the Jupyter notebook)
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle
import json
import plotly.express as px
import plotly.graph_objects as go

#-----------------------------
# Page configuration
#-----------------------------
st.set_page_config(
    page_title="AutoValuator",
    page_icon="🚗",
    layout="wide",
)

#-----------------------------
# Load (cached so load once)
#-----------------------------
@st.cache_resource                          # FIX: cache_resource for pickle objects
def load_model():
    with open("models/model.pkl", "rb") as f:
        return pickle.load(f)

@st.cache_resource
def load_encoder():
    with open("models/encoder.pkl", "rb") as f:
        return pickle.load(f)

@st.cache_data
def load_meta():
    with open("feature_meta.json", "r") as f:
        return json.load(f)

@st.cache_data
def load_data():
    df = pd.read_csv("data/cars_bids_clean.csv")
    return df

model   = load_model()
encoder = load_encoder()
meta    = load_meta()
df      = load_data()

CAT_FEATURES = meta["categorical_features"]
NUM_FEATURES = meta["numeric_features"]     # FIX 2: was "numerical_features"
ALL_FEATURES = meta["all_features"]
CATEGORIES   = meta["categories"]
METRICS      = meta["model_metrics"]

#-----------------------------
# Helper functions
#-----------------------------
def predict_price(inputs: dict) -> float:
    """Run model on a dict of raw inputs & return predicted price."""
    row = pd.DataFrame([inputs])            # FIX 10: [inputs] not inputs
    row[CAT_FEATURES] = encoder.transform(row[CAT_FEATURES])
    pred_log = model.predict(row[ALL_FEATURES].values)[0]
    return float(np.expm1(pred_log))        # reverse log transform


#-----------------------------
# Header
#-----------------------------
st.title("AutoValuator")
st.caption("Auction price predictor & market dashboard powered by 3000 real auctions.")

col1, col2, col3 = st.columns(3)
col1.metric("Model R²",        f"{METRICS['r2']:.3f}")          # FIX 1: metric not metrics
col2.metric("Avg Error (MAE)", f"${METRICS['mae']:,.0f}")        # FIX 1
col3.metric("RMSE",            f"${METRICS['rmse']:,.0f}")       # FIX 1

st.divider()

#-----------------------------
# Tabs
#-----------------------------
tab1, tab2, tab3, tab4 = st.tabs([
    "🔮 Price Estimator",
    "📊 Market Dashboard",
    "🔍 Deal Scorer",
    "🗂️ Data Explorer",
])

#-----------------------------
# Tab 1: Price Estimator
#-----------------------------
with tab1:
    st.subheader("Predict an Auction Sale Price")
    st.write("Fill in the car's details to get a model predicted auction price.")

    col_a, col_b = st.columns(2)

    with col_a:
        make = st.selectbox("Make", CATEGORIES["make"])

        # Filter models to only show those belonging to selected make
        available_models = sorted(df[df["make"] == make]["model"].dropna().unique().tolist())
        car_model = st.selectbox("Model", available_models)

        body_style = st.selectbox("Body Style", CATEGORIES["body_style"])
        transmission_clean = st.selectbox("Transmission", CATEGORIES["transmission_clean"])
        drivetrain_clean = st.selectbox("Drivetrain", CATEGORIES["drivetrain_clean"])
        seller_type = st.selectbox("Seller Type", CATEGORIES["seller_type_clean"])

    with col_b:
        year          = st.slider("Year", min_value=1980, max_value=2026, value=2005)
        mileage_clean = st.number_input("Mileage", min_value=0, max_value=500_000, value=45_000, step=1_000)
        bids          = st.slider("Expected bids", min_value=0, max_value=100, value=20)

    is_high_mileage = int(mileage_clean > 100_000)
    is_manual       = int(transmission_clean == "Manual")
    is_rwd          = int(drivetrain_clean == "RWD")
    is_private      = int(seller_type == "Private Party")

    inputs = {
        "make":               make,
        "model":              car_model,           # FIX 3: added model
        "body_style":         body_style,
        "transmission_clean": transmission_clean,
        "drivetrain_clean":   drivetrain_clean,
        "seller_type_clean":  seller_type,
        "year":               year,
        "mileage_clean":      mileage_clean,
        "bids_clean":         bids,
        "is_manual":          is_manual,
        "is_rwd":             is_rwd,
        "is_private_seller":  is_private,
        "is_high_mileage":    is_high_mileage,
    }

    if st.button("📐 Predict Price", type="primary", use_container_width=True):
        pred = predict_price(inputs)
        low, high = pred * 0.85, pred * 1.15

        st.success(f"Predicted Auction Price: ${pred:,.0f}")

        col_r1, col_r2, col_r3 = st.columns(3)
        col_r1.metric("Conservative (−15%)", f"${low:,.0f}")
        col_r2.metric("Prediction",           f"${pred:,.0f}", delta="model estimate")
        col_r3.metric("Optimistic (+15%)",    f"${high:,.0f}")

        # Comparable sold cars
        st.markdown("### Similar cars that sold")
        similar = df[
            (df['make'] == make) &
            (df['transmission_clean'] == transmission_clean) &
            (df['mileage_clean'].between(mileage_clean * 0.7, mileage_clean * 1.3))
        ][["title", "year", "mileage_clean", "sale_price", "bids_clean"]].sort_values(
            "sale_price", ascending=False).head(8)

        if len(similar):
            similar.columns = ["Title", "Year", "Mileage", "Sale Price ($)", "Bids"]
            similar["Sale Price ($)"] = similar["Sale Price ($)"].apply(lambda x: f"${x:,.0f}")
            similar["Mileage"]        = similar["Mileage"].apply(lambda x: f"{x:,.0f}")   # FIX 8: correct column name
            st.dataframe(similar, use_container_width=True, hide_index=True)
        else:
            st.info("No close matches found in the dataset — try relaxing the filters.")

#-----------------------------
# Tab 2: Market Dashboard
#-----------------------------
with tab2:
    st.subheader("Market Intelligence Dashboard")

    c1, c2 = st.columns([2, 1])
    with c1:
        selected_make = st.multiselect(
            "Filter by make",
            options=sorted(df["make"].dropna().unique()),
        )
    with c2:
        min_price, max_price = int(df["sale_price"].min()), int(df["sale_price"].max())
        price_range = st.slider("Price range ($)", min_price, max_price,
                                (min_price, 150_000), step=1_000)

    plot_df = df.copy()
    if selected_make:
        plot_df = plot_df[plot_df["make"].isin(selected_make)]
    plot_df = plot_df[plot_df["sale_price"].between(*price_range)]
    plot_df = plot_df[plot_df["sale_price"] > 0]
    plot_df = plot_df.dropna(subset=["sale_price", "mileage_clean", "car_age", "body_style"])

    r1c1, r1c2 = st.columns(2)

    # Price distribution
    with r1c1:
        fig = px.histogram(
            plot_df, x="sale_price", nbins=60,
            title="Sale Price Distribution",
            labels={"sale_price": "Sale Price ($)"},
            color_discrete_sequence=["steelblue"],
        )
        fig.update_layout(bargap=0.05, showlegend=False)
        st.plotly_chart(fig, use_container_width=True)

    # Median price by make
    with r1c2:
        top_makes = (
            plot_df.groupby("make")["sale_price"]
            .median().sort_values(ascending=False).head(15).reset_index()
        )
        fig2 = px.bar(
            top_makes, x="make", y="sale_price",
            title="Median Sale Price by Make (Top 15)",
            labels={"make": "", "sale_price": "Median Price ($)"},
            color="sale_price",                     # FIX 5: color not colors
            color_continuous_scale="Blues",
        )
        fig2.update_layout(xaxis_tickangle=-35, coloraxis_showscale=False)  # FIX 6: showscale not showcase
        st.plotly_chart(fig2, use_container_width=True)

    r2c1, r2c2 = st.columns(2)

    # Mileage vs Price scatter
    with r2c1:
        scatter_df = plot_df[plot_df["mileage_clean"] < 250_000]
        fig3 = px.scatter(
            scatter_df, x="mileage_clean", y="sale_price",
            color="car_age", color_continuous_scale="RdYlGn_r",
            title="Mileage vs Sale Price",
            labels={"mileage_clean": "Mileage", "sale_price": "Sale Price ($)", "car_age": "Age"},
            opacity=0.5, size_max=4,
        )
        st.plotly_chart(fig3, use_container_width=True)

    # Transmission type breakdown
    with r2c2:
        fig4 = px.box(
            plot_df, x="transmission_clean", y="sale_price",
            color="transmission_clean",
            title="Sale Price by Transmission Type",
            labels={"transmission_clean": "Transmission", "sale_price": "Sale Price ($)"},
        )
        fig4.update_layout(showlegend=False)
        st.plotly_chart(fig4, use_container_width=True)

    # Body style volume
    st.markdown("### Auction Volume & Median Price by Body Style")
    body_stats = (
        plot_df.groupby("body_style")
        .agg(
            count=("sale_price", "count"),
            median_price=("sale_price", "median")
        ).sort_values("count", ascending=False).reset_index()  # FIX 7: sort_values not sortvalues
    )
    fig5 = px.scatter(
        body_stats, x="count", y="median_price", text="body_style",
        size="count", color="median_price", color_continuous_scale="Blues",
        title="Body Style: Volume vs Median Price",
        labels={"count": "Number of Auctions", "median_price": "Median Price ($)"},
    )
    fig5.update_traces(textposition="top center")
    fig5.update_layout(coloraxis_showscale=False)
    st.plotly_chart(fig5, use_container_width=True)

#-----------------------------
# Tab 3: Deal Scorer
#-----------------------------
with tab3:
    st.subheader("Deal Scorer")
    st.write(
        "Enter the details of a car you're considering. "
        "The scorer compares the **asking price** to the model's predicted market value."
    )

    col_ds1, col_ds2 = st.columns(2)

    with col_ds1:
        ds_make   = st.selectbox("Make",         CATEGORIES["make"],               key="ds_make")
        ds_available_models = sorted(df[df["make"] == ds_make]["model"].dropna().unique().tolist())# Filter models by selected make
        ds_model = st.selectbox("Model", ds_available_models, key="ds_model")
        ds_body   = st.selectbox("Body Style",   CATEGORIES["body_style"],         key="ds_body")
        ds_trans  = st.selectbox("Transmission", CATEGORIES["transmission_clean"], key="ds_trans")
        ds_drive  = st.selectbox("Drivetrain",   CATEGORIES["drivetrain_clean"],   key="ds_drive")
        ds_seller = st.selectbox("Seller Type",  CATEGORIES["seller_type_clean"],  key="ds_seller")

    with col_ds2:
        ds_year    = st.slider("Year",          1980, 2026, 2005, key="ds_year")
        ds_mileage = st.number_input("Mileage", 0, 500_000, 45_000, 1_000, key="ds_mileage")
        ds_bids    = st.slider("Expected bids", 0, 100, 20, key="ds_bids")
        ds_asking  = st.number_input("Listing / Asking Price ($)", 500, 1_000_000, 25_000, 500)

    if st.button("🎯 Score this Deal", type="primary", use_container_width=True):
        ds_input = {
            "make":               ds_make,
            "model":              ds_model,        # FIX 4: added
            "body_style":         ds_body,
            "transmission_clean": ds_trans,
            "drivetrain_clean":   ds_drive,
            "seller_type_clean":  ds_seller,
            "year":               ds_year,
            "mileage_clean":      ds_mileage,
            "bids_clean":         ds_bids,
            "is_manual":          int(ds_trans == "Manual"),
            "is_rwd":             int(ds_drive == "RWD"),
            "is_private_seller":  int(ds_seller == "Private Party"),
            "is_high_mileage":    int(ds_mileage > 100_000),
        }
        pred_val = predict_price(ds_input)
        diff     = ds_asking - pred_val
        pct_diff = diff / pred_val * 100

        st.divider()
        col_v1, col_v2, col_v3 = st.columns(3)
        col_v1.metric("Predicted Market Value", f"${pred_val:,.0f}")
        col_v2.metric("Asking Price",            f"${ds_asking:,.0f}")
        col_v3.metric("Difference",              f"${diff:+,.0f}", delta=f"{pct_diff:+.1f}%",
                      delta_color="inverse")

        if pct_diff < -10:
            st.success(f"🟢 **Great deal!** Asking price is {abs(pct_diff):.1f}% below predicted market value.")
        elif pct_diff < 5:
            st.info(f"🔵 **Fair price.** Asking is within normal range of predicted value.")
        elif pct_diff < 20:
            st.warning(f"🟡 **Slightly above market.** Asking is {pct_diff:.1f}% above predicted value.")
        else:
            st.error(f"🔴 **Overpriced.** Asking is {pct_diff:.1f}% above predicted market value.")

        # FIX 9: gauge is outside the else block — always shows after scoring
        fig_gauge = go.Figure(go.Indicator(
            mode="gauge+number+delta",
            value=ds_asking,
            delta={"reference": pred_val, "relative": True, "valueformat": ".1%"},
            title={"text": "Asking vs Predicted"},
            gauge={
                "axis": {"range": [pred_val * 0.5, pred_val * 1.5]},
                "bar": {"color": "steelblue"},
                "steps": [
                    {"range": [pred_val * 0.5, pred_val * 0.9], "color": "#c3e6c3"},
                    {"range": [pred_val * 0.9, pred_val * 1.1], "color": "#fff3cd"},
                    {"range": [pred_val * 1.1, pred_val * 1.5], "color": "#f8d7da"},
                ],
                "threshold": {
                    "line": {"color": "black", "width": 2},
                    "thickness": 0.75,
                    "value": pred_val,
                },
            },
        ))
        fig_gauge.update_layout(height=300)
        st.plotly_chart(fig_gauge, use_container_width=True)

#-----------------------------
# Tab 4: Data Explorer
#-----------------------------
with tab4:
    st.subheader("Data Explorer")
    st.write("Browse, filter, and sort the cleaned auction dataset.")

    ec1, ec2, ec3 = st.columns(3)
    with ec1:
        flt_make  = st.multiselect("Make",         sorted(df["make"].dropna().unique()),               key="exp_make")
    with ec2:
        flt_body  = st.multiselect("Body Style",   sorted(df["body_style"].dropna().unique()),         key="exp_body")
    with ec3:
        flt_trans = st.multiselect("Transmission", sorted(df["transmission_clean"].dropna().unique()), key="exp_trans")

    exp_df = df.copy()
    if flt_make:  exp_df = exp_df[exp_df["make"].isin(flt_make)]
    if flt_body:  exp_df = exp_df[exp_df["body_style"].isin(flt_body)]
    if flt_trans: exp_df = exp_df[exp_df["transmission_clean"].isin(flt_trans)]

    st.caption(f"Showing **{len(exp_df):,}** records")

    display_cols = ["title", "make", "body_style", "year", "mileage_clean",
                    "transmission_clean", "drivetrain_clean", "bids_clean", "sale_price"]
    exp_show = exp_df[display_cols].copy()
    exp_show.columns = ["Title", "Make", "Body", "Year", "Mileage",
                        "Transmission", "Drivetrain", "Bids", "Sale Price ($)"]
    exp_show["Sale Price ($)"] = exp_show["Sale Price ($)"].apply(
        lambda x: f"${x:,.0f}" if pd.notna(x) else "—"
    )
    exp_show["Mileage"] = exp_show["Mileage"].apply(
        lambda x: f"{x:,.0f}" if pd.notna(x) else "—"
    )

    st.dataframe(exp_show, use_container_width=True, hide_index=True, height=500)

    st.download_button(
        label="⬇ Download filtered data as CSV",
        data=exp_df.to_csv(index=False).encode("utf-8"),
        file_name="cars_bids_filtered.csv",
        mime="text/csv",
    )